2020-10-14 10:38:38,031 - trace.py[line:122] - INFO: Task cc.add[28958f9e-60bb-4444-8f42-8a714f5005ed] succeeded in 6.013002909952775s: 4
